import type {
  AvatarProfile,
  CeoIdentity,
  EmployeeOperationalState,
  EmployeeSpatialState,
  MeetingRoomState,
  OfficePosition,
} from '../types/office';

export const CEO_IDENTITY: CeoIdentity = {
  id: 'ceo',
  name: 'Matheus Paes',
  title: 'Diretor Executivo / Comandante do PUB DEV LOOP',
  role: 'CEO',
  status: 'ACTIVE',
  specialty: 'Direção Estratégica, Visão de Produto & Autoridade Soberana',
  personalitySummary: 'Líder estratégico focado em entregas de alto impacto e governança rigorosa. Valoriza autonomia, velocidade e arquiteturas limpas sem tolerar burocracia vazia.',
  operationalState: 'idle',
  spatialState: 'idle',
  facingDirection: 'SOUTH',
  position: {
    zoneId: 'CEO_SUITE',
    zoneName: 'Gabinete Executivo do CEO',
    deskId: 'mesa-executiva-ceo',
    deskLabel: 'Mesa Principal do CEO',
    floor: 3,
    facingDirection: 'SOUTH',
    coordinates: { x: 50, y: 15 },
  },
  avatar: {
    avatarId: 'avatar-ceo',
    displayName: 'Matheus Paes',
    roleLabel: 'CEO & Fundador',
    badgeIcon: '👑',
    accentColor: '#8b5cf6',
    initials: 'MP',
    hairColor: '#334155',
    suitColor: '#1e1b4b',
    tieColor: '#7c3aed',
    avatarStyle: 'EXECUTIVE',
    age: 32,
    nickname: 'O Comandante',
    drinkPreference: 'Espresso duplo sem açúcar',
    musicTaste: 'Synthwave & Lo-Fi Beats',
    catchphrase: 'Menos burocracia, mais código de verdade em produção.',
    knownQuirks: ['Gosta de acompanhar logs em tempo real', 'Toca clássicos no vinil nas sextas-feiras'],
    rivalries: 'Inimigo mortal do Fake Activity e de processos engessados.',
    backgroundLore: 'Engenheiro e fundador obstinado que construiu o THE OFFICE para ser a empresa de IA mais eficiente e divertida do planeta.',
  },
};

export const INITIAL_MEETING_ROOM: MeetingRoomState = {
  id: 'sala-alinhamento-principal',
  name: 'Sala de Alinhamento & Estratégia',
  status: 'DISPONIVEL',
  participants: [],
};

export const AGENT_AVATAR_PROFILES: Record<string, AvatarProfile> = {
  'chief-of-staff': {
    avatarId: 'avatar-chief-of-staff',
    displayName: 'Dr. Arthur Vance',
    roleLabel: 'Chief of Staff & Orquestrador',
    badgeIcon: '👔',
    accentColor: '#f59e0b',
    initials: 'AV',
    hairColor: '#451a03',
    suitColor: '#291e17',
    tieColor: '#d97706',
    accessory: '👓',
    avatarStyle: 'STRATEGY',
    age: 52,
    nickname: 'O Diplomata',
    drinkPreference: 'Café coado na porcelana, sem açúcar',
    musicTaste: 'Jazz Tradicional & Bossa Nova',
    catchphrase: 'Alinhamento e governança evitam retrabalho. O CEO precisa de previsibilidade.',
    knownQuirks: ['Organiza a bancada por ordem alfabética', 'Anota tudo com caneta-tinteiro virtual'],
    rivalries: 'Acha que o Lucas (Dev) é impulsivo demais e vive cobrando cronogramas que nunca são seguidos à risca.',
    backgroundLore: 'Veterano de consultorias multinacionais, Dr. Arthur é a ponte perfeita entre a visão do CEO e o caos criativo da equipe de engenharia.',
  },
  architect: {
    avatarId: 'avatar-architect',
    displayName: 'Helena Rostova',
    roleLabel: 'Principal Systems Architect',
    badgeIcon: '📐',
    accentColor: '#3b82f6',
    initials: 'HR',
    hairColor: '#1e293b',
    suitColor: '#172554',
    tieColor: '#2563eb',
    accessory: '📐',
    avatarStyle: 'ARCHITECT',
    age: 39,
    nickname: 'Vektor',
    drinkPreference: 'Chá Earl Grey com gotas de limão',
    musicTaste: 'IDM & Techno Minimalista',
    catchphrase: 'Se a abstração estiver errada, todo o resto é apenas uma ilusão funcional.',
    knownQuirks: ['Desenha diagramas UML no ar enquanto pensa', 'Recusa-se a usar any no TypeScript mesmo sob tortura'],
    rivalries: 'Vive em pé de guerra com o Lucas (Dev), chamando os workarounds rápidos dele de "gambiarras amarradas com barbante".',
    backgroundLore: 'Cientista da computação teórica e ex-hacker de sistemas distribuídos de alta escala. Considera arquitetura limpa uma forma superior de arte.',
  },
  developer: {
    avatarId: 'avatar-developer',
    displayName: 'Lucas Silveira',
    roleLabel: 'Senior Full-Stack Developer',
    badgeIcon: '💻',
    accentColor: '#0ea5e9',
    initials: 'LS',
    hairColor: '#0f172a',
    suitColor: '#082f49',
    tieColor: '#0284c7',
    accessory: '🎧',
    avatarStyle: 'CODER',
    age: 28,
    nickname: 'Crash',
    drinkPreference: 'Energético gelado + café frio da garrafa',
    musicTaste: 'Heavy Metal & Synthwave Acelerado',
    catchphrase: 'Funciona na minha máquina e passa no build. Sobe logo isso antes que mude o universo!',
    knownQuirks: ['Digita a 120 palavras por minuto ouvindo riff de guitarra', 'Sempre jura que "esse é o último hotfix"'],
    rivalries: 'Reclama que a Helena cria 15 camadas de abstração antes de escrever um console.log e que a Beatriz é chata com linter.',
    backgroundLore: 'Autodidata brilhante, viciado em maratonas de código e em resolver bugs insolúveis na velocidade da luz.',
  },
  reviewer: {
    avatarId: 'avatar-reviewer',
    displayName: 'Beatriz Mendes',
    roleLabel: 'Staff Security & Code Reviewer',
    badgeIcon: '🔍',
    accentColor: '#10b981',
    initials: 'BM',
    hairColor: '#14532d',
    suitColor: '#052e16',
    tieColor: '#059669',
    accessory: '🔍',
    avatarStyle: 'REVIEWER',
    age: 34,
    nickname: 'Sentinel',
    drinkPreference: 'Chá verde matcha e água com gás',
    musicTaste: 'Lo-Fi Chillhop & Dark Ambient',
    catchphrase: 'Aprovado apenas quando a segurança for matematicamente inquestionável. Corrija o PR, Lucas.',
    knownQuirks: ['Encontra memory leaks olhando o código por 3 segundos', 'Seu sarcasmo em code reviews é uma obra-prima'],
    rivalries: 'Tem imenso prazer profissional em bloquear PRs descuidados do Lucas e apontar brechas de segurança sutis.',
    backgroundLore: 'Especialista em computação forense e segurança ofensiva/defensiva. Nenhuma vulnerabilidade passa pelo seu filtro.',
  },
  'qa-engineer': {
    avatarId: 'avatar-qa-engineer',
    displayName: 'Tiago Rocha',
    roleLabel: 'Chaos QA & Automation Engineer',
    badgeIcon: '🧪',
    accentColor: '#059669',
    initials: 'TR',
    hairColor: '#064e3b',
    suitColor: '#022c22',
    tieColor: '#10b981',
    accessory: '🧪',
    avatarStyle: 'QA',
    age: 31,
    nickname: 'Chaos',
    drinkPreference: 'Refrigerante de cola zero e café muito doce',
    musicTaste: 'Chiptune & Eletrônica 8-bit',
    catchphrase: 'Se o usuário conseguir quebrar, eu preciso quebrar primeiro. Onde está o teste de estresse?',
    knownQuirks: ['Tem 8 patinhos de borracha amarelos na mesa', 'Testa campos de formulário colando a Bíblia inteira em japonês'],
    rivalries: 'Adora mandar prints de tela vermelha com crashes no Slack às 17h55 de uma sexta-feira para provocar o Lucas.',
    backgroundLore: 'Ex-auditor de qualidade aeroespacial, apaixonado por engenharia do caos e por garantir que nenhum edge case fique impune.',
  },
};

export const AGENT_OFFICE_POSITIONS: Record<string, OfficePosition> = {
  'chief-of-staff': {
    zoneId: 'LEADERSHIP',
    zoneName: 'Suíte de Liderança & Orquestração',
    deskId: 'mesa-chief-of-staff',
    deskLabel: 'Estação da Chefia de Gabinete',
    floor: 3,
    facingDirection: 'SOUTH',
    coordinates: { x: 50, y: 35 },
  },
  architect: {
    zoneId: 'ENGINEERING',
    zoneName: 'Laboratório de Engenharia de Software',
    deskId: 'mesa-architect',
    deskLabel: 'Bancada de Arquitetura',
    floor: 3,
    facingDirection: 'EAST',
    coordinates: { x: 30, y: 65 },
  },
  developer: {
    zoneId: 'ENGINEERING',
    zoneName: 'Laboratório de Engenharia de Software',
    deskId: 'mesa-developer',
    deskLabel: 'Bancada de Desenvolvimento',
    floor: 3,
    facingDirection: 'WEST',
    coordinates: { x: 70, y: 65 },
  },
  reviewer: {
    zoneId: 'QA',
    zoneName: 'Laboratório de Revisão & Qualidade',
    deskId: 'mesa-reviewer',
    deskLabel: 'Bancada de Code Review & Segurança',
    floor: 3,
    facingDirection: 'EAST',
    coordinates: { x: 30, y: 85 },
  },
  'qa-engineer': {
    zoneId: 'QA',
    zoneName: 'Laboratório de Revisão & Qualidade',
    deskId: 'mesa-qa-engineer',
    deskLabel: 'Bancada de Testes & Automação',
    floor: 3,
    facingDirection: 'WEST',
    coordinates: { x: 70, y: 85 },
  },
};

export const OPERATIONAL_STATE_LABELS_PT: Record<EmployeeOperationalState, { label: string; tagCls: string }> = {
  idle: { label: 'Disponível', tagCls: 'state-idle' },
  working: { label: 'Executando Tarefa', tagCls: 'state-working' },
  thinking: { label: 'Formulando Plano', tagCls: 'state-thinking' },
  reviewing: { label: 'Revisando Código', tagCls: 'state-reviewing' },
  collaborating: { label: 'Em Colaboração', tagCls: 'state-collaborating' },
  in_meeting: { label: 'Em Reunião de Alinhamento', tagCls: 'state-meeting' },
  waiting_for_dependency: { label: 'Aguardando Dependência', tagCls: 'state-waiting' },
  waiting_for_approval: { label: 'Aguardando Aprovação do CEO', tagCls: 'state-waiting' },
  celebrating: { label: 'Entrega Concluída', tagCls: 'state-celebrating' },
  learning: { label: 'Consolidando Aprendizado', tagCls: 'state-learning' },
  offline: { label: 'Desconectado', tagCls: 'state-offline' },
  blocked: { label: 'Bloqueado', tagCls: 'state-blocked' },
};

export const SPATIAL_STATE_LABELS_PT: Record<EmployeeSpatialState, { label: string; tagCls: string }> = {
  idle: { label: 'Na Estação', tagCls: 'spatial-idle' },
  walking: { label: 'Em Deslocamento', tagCls: 'spatial-walking' },
  approaching: { label: 'Aproximando-se', tagCls: 'spatial-approaching' },
  interacting: { label: 'Em Interação', tagCls: 'spatial-interacting' },
  returning: { label: 'Retornando ao Posto', tagCls: 'spatial-returning' },
};
