/**
 * Phase 7: Complexity-Triggered Planning V1 (Candidate A).
 *
 * Deterministic complexity classification contract and types.
 * Authoritative specification: docs/evidence/phase6/COMPLEXITY_TRIGGERED_PLANNING_SPEC.md
 */

export type TaskComplexityTier = 'SIMPLE' | 'COMPLEX';

export type HardComplexitySignal =
  | 'HARD_01_LIFECYCLE_CORE'
  | 'HARD_02_PERSISTENCE_SCHEMA'
  | 'HARD_03_BREAKING_CONTRACT'
  | 'HARD_04_CIRCULAR_DEP_REFACTOR'
  | 'HARD_05_SECURITY_AUTH';

export type SoftComplexitySignal =
  | 'SOFT_01_MULTI_FILE'
  | 'SOFT_02_PROMPT_LENGTH'
  | 'SOFT_03_MULTIPLE_ACCEPTANCE'
  | 'SOFT_04_ASYNC_CONCURRENCY'
  | 'SOFT_05_ERROR_HANDLING_DEPTH'
  | 'SOFT_06_PREVIOUS_FAILURE'
  | 'SOFT_07_ESTIMATED_DIFF_LOC';

export interface SoftSignalTrigger {
  signal: SoftComplexitySignal;
  weight: number;
  evidence: string;
}

export interface ComplexityClassificationDecision {
  classifierVersion: '1.0.0';
  taskId: string;
  tier: TaskComplexityTier;
  planningRequired: boolean;
  hardSignalsTriggered: HardComplexitySignal[];
  softSignalsTriggered: SoftSignalTrigger[];
  softSignalScore: number;
  softSignalThreshold: number;
  decisionRationale: string;
  evaluationDurationMs: number;
  evaluatedAt: string;
}

/**
 * StructuredExecutionPlan contract.
 * Generated by the planner during planning-required attempts.
 */
export interface ImplementationStep {
  stepNumber: number;
  description: string;
  targetFile: string;
}

export interface StructuredExecutionPlan {
  planVersion: '1.0.0';
  taskId: string;
  attempt: number;
  goal: string;
  filesToChange: string[];
  dependencies: string[];
  implementationSteps: ImplementationStep[];
  testStrategy: string[];
  riskPoints: string[];
  rollbackConsiderations: string[];
  complexityAssessment: string;
}

/**
 * Plan Validation Results
 */
export interface PlanValidationError {
  stage: 1 | 2 | 3 | 4;
  stageName: 'STRUCTURAL' | 'SCOPE_CONTAINMENT' | 'GOVERNANCE' | 'TEST_STRATEGY';
  message: string;
  fatal: boolean; // Stage 2 & 3 are always fatal (no revision permitted)
}

export interface PlanValidationResult {
  valid: boolean;
  errors: PlanValidationError[];
  revisionAllowed: boolean;
  validatedPlan?: StructuredExecutionPlan;
}

/**
 * Feature flag / rollout mode for Complexity-Triggered Planning.
 * OFF: Legacy direct execution, zero overhead.
 * SHADOW: Deterministic classification + event logging, but no planning execution blocking.
 * CANARY: Planning active for canary target products (e.g. pub-dev-loop-template).
 * FULL: Planning active for all products.
 */
export type ComplexityPlanningMode = 'OFF' | 'SHADOW' | 'CANARY' | 'FULL';
