/**
 * Phase 3B — Atomic Executable Task Intake Tests
 *
 * Verifies:
 * 1. successful atomic intake
 * 2. Task + SEALED ExecutionSpec
 * 3. rollback on task failure
 * 4. rollback on createExecutionSpec failure
 * 5. rollback on sealExecutionSpec failure
 * 6. client release on success
 * 7. client release on failure
 * 8. HTTP 201
 * 9. HTTP 400
 * 10. HTTP 422
 * 11. HTTP 500
 * 12. no duplicate sealing mechanism
 * 13. no direct SEALED insert
 * 14. lineage preserved
 * 15. intakeHash preserved
 * 16. specHash generated by canonical seal
 * 17. Task remains QUEUED
 * 18. historical Tasks untouched
 * 19. PP remains isolated
 * 20. no migration required
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import type { Server } from 'http';
import {
  TaskIntakeService,
  buildCanonicalExecutionSpec,
  type PoolClientLike,
  type PoolLike,
} from '../../src/pdl/service/task-intake-service.js';
import { createPdlApp } from '../../src/pdl/api/entry.js';
import { normalizeTaskIntake } from '../../src/task/intake.js';
import {
  computeSpecHash,
  type ExecutionSpecRecord,
} from '../../src/execution/execution-spec-persistence.js';
import { EXECUTION_SPEC_VERSION } from '../../src/task/execution-spec.js';
import type { Task } from '../../src/domain.js';

interface MockDbState {
  tasks: Map<string, any>;
  specs: Map<string, any>;
  transactionsBegan: number;
  transactionsCommitted: number;
  transactionsRolledBack: number;
  clientsReleased: number;
  failAtTaskInsert?: boolean;
  failAtCreateSpec?: boolean;
  failAtSealSpec?: boolean;
  failAtCommit?: boolean;
  recordedSpecStatusesOnInsert: string[];
}

function createMockTransactionalPool(initialState?: Partial<MockDbState>): {
  pool: PoolLike;
  state: MockDbState;
} {
  const state: MockDbState = {
    tasks: new Map(),
    specs: new Map(),
    transactionsBegan: 0,
    transactionsCommitted: 0,
    transactionsRolledBack: 0,
    clientsReleased: 0,
    recordedSpecStatusesOnInsert: [],
    ...initialState,
  };

  const pool: PoolLike = {
    connect: async (): Promise<PoolClientLike> => {
      // Per-connection transaction buffer
      let inTx = false;
      const txTasks = new Map<string, any>();
      const txSpecs = new Map<string, any>();

      const client: PoolClientLike = {
        release: () => {
          state.clientsReleased++;
        },
        query: async (sql: string, params?: unknown[]): Promise<{ rows: any[] }> => {
          const upper = sql.trim().toUpperCase();

          if (upper.startsWith('BEGIN')) {
            inTx = true;
            state.transactionsBegan++;
            return { rows: [] };
          }

          if (upper.startsWith('COMMIT')) {
            if (state.failAtCommit) {
              throw new Error('Simulated database COMMIT failure');
            }
            // Commit buffer into permanent store
            for (const [k, v] of txTasks) state.tasks.set(k, v);
            for (const [k, v] of txSpecs) state.specs.set(k, v);
            inTx = false;
            state.transactionsCommitted++;
            return { rows: [] };
          }

          if (upper.startsWith('ROLLBACK')) {
            // Discard transaction buffer
            txTasks.clear();
            txSpecs.clear();
            inTx = false;
            state.transactionsRolledBack++;
            return { rows: [] };
          }

          // INSERT INTO tasks
          if (sql.includes('INSERT INTO tasks')) {
            if (state.failAtTaskInsert) {
              throw new Error('Simulated tasks table INSERT failure');
            }
            const [project, repository, objective, prompt, priority, status] = (params || []) as any[];
            const id = 'task-' + Date.now() + '-' + Math.random().toString(36).slice(2, 9);
            const row = {
              id,
              project,
              repository,
              objective,
              prompt,
              priority: priority ?? 0,
              status: status ?? 'QUEUED',
              worker: null,
              result: null,
              error: null,
              branch: null,
              commit_sha: null,
              git_status: null,
              created_at: new Date(),
              updated_at: new Date(),
              lease_owner: null,
              lease_deadline: null,
              heartbeat_at: null,
              workspace_path: null,
              prototype_session_id: null,
            };
            if (inTx) txTasks.set(id, row);
            else state.tasks.set(id, row);
            return { rows: [row] };
          }

          // SELECT FROM execution_specs
          if (sql.includes('SELECT') && sql.includes('execution_specs')) {
            const taskId = params?.[0];
            const found =
              (inTx ? txSpecs.get(taskId as string) : undefined) ??
              state.specs.get(taskId as string);
            return { rows: found ? [found] : [] };
          }

          // INSERT INTO execution_specs
          if (sql.includes('INSERT INTO execution_specs')) {
            if (state.failAtCreateSpec) {
              throw new Error('Simulated execution_specs table INSERT failure');
            }
            const [
              id,
              task_id,
              spec_version,
              spec_hash,
              objective,
              lineageStr,
              status,
              created_at,
              sealed_at,
              spec_content_json,
            ] = (params || []) as any[];

            state.recordedSpecStatusesOnInsert.push(status);

            const row = {
              id,
              task_id,
              spec_version,
              spec_hash,
              objective,
              lineage: typeof lineageStr === 'string' ? JSON.parse(lineageStr) : lineageStr,
              status,
              created_at: new Date(created_at),
              sealed_at: sealed_at ? new Date(sealed_at) : null,
              spec_content_json,
            };

            if (inTx) txSpecs.set(task_id, row);
            else state.specs.set(task_id, row);
            return { rows: [row] };
          }

          // UPDATE execution_specs
          if (sql.includes('UPDATE execution_specs')) {
            if (state.failAtSealSpec) {
              throw new Error('Simulated execution_specs table SEAL UPDATE failure');
            }
            const [status, sealed_at, spec_hash, spec_content_json, task_id] = (params || []) as any[];
            const existing =
              (inTx ? txSpecs.get(task_id as string) : undefined) ??
              state.specs.get(task_id as string);

            if (!existing) {
              throw new Error('Record for task ' + task_id + ' not found');
            }

            const updated = {
              ...existing,
              status,
              sealed_at: sealed_at ? new Date(sealed_at) : existing.sealed_at,
              spec_hash: spec_hash ?? existing.spec_hash,
              spec_content_json: spec_content_json ?? existing.spec_content_json,
            };

            if (inTx) txSpecs.set(task_id, updated);
            else state.specs.set(task_id, updated);
            return { rows: [updated] };
          }

          return { rows: [] };
        },
      };

      return client;
    },
  };

  return { pool, state };
}

describe('Phase 3B — Atomic Executable Task Intake', () => {
  describe('A. Core Atomic Lifecycle & Persistence Invariants', () => {
    it('1. successful atomic intake: creates Task + SEALED ExecutionSpec in single transaction', async () => {
      const { pool, state } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const result = await service.processIntake({
        rawRequest: 'Implement user password reset via email',
        source: 'pdl-api',
        project: 'pub-auth',
        repository: 'https://github.com/pubcoreagencia/pub-auth.git',
        priority: 2,
      });

      expect(result).toBeDefined();
      expect(result.task).toBeDefined();
      expect(result.executionSpec).toBeDefined();

      // State verification
      expect(state.transactionsBegan).toBe(1);
      expect(state.transactionsCommitted).toBe(1);
      expect(state.transactionsRolledBack).toBe(0);
      expect(state.clientsReleased).toBe(1);

      // Verify committed records
      expect(state.tasks.has(result.task.id)).toBe(true);
      expect(state.specs.has(result.task.id)).toBe(true);
    });

    it('2. Task + SEALED ExecutionSpec: verifies Task QUEUED and spec SEALED with timestamp', async () => {
      const { pool, state } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const result = await service.processIntake({
        rawRequest: 'Setup automated deployment pipeline',
      });

      // Task invariants
      expect(result.task.status).toBe('QUEUED');
      expect(result.task.id).toMatch(/^task-/);
      expect(result.task.objective).toBe('Setup automated deployment pipeline');

      // Spec invariants
      expect(result.executionSpec.status).toBe('SEALED');
      expect(result.executionSpec.task_id).toBe(result.task.id);
      expect(result.executionSpec.sealed_at).toBeDefined();
      expect(typeof result.executionSpec.sealed_at).toBe('string');
      expect(result.executionSpec.spec_hash.length).toBeGreaterThan(10);
    });

    it('3. rollback on task failure: zero Task and zero ExecutionSpec persisted', async () => {
      const { pool, state } = createMockTransactionalPool({ failAtTaskInsert: true });
      const service = new TaskIntakeService(pool);

      await expect(
        service.processIntake({ rawRequest: 'Will fail on task insert' })
      ).rejects.toThrow('Simulated tasks table INSERT failure');

      expect(state.transactionsBegan).toBe(1);
      expect(state.transactionsCommitted).toBe(0);
      expect(state.transactionsRolledBack).toBe(1);
      expect(state.clientsReleased).toBe(1);
      expect(state.tasks.size).toBe(0);
      expect(state.specs.size).toBe(0);
    });

    it('4. rollback on createExecutionSpec failure: zero Task and zero ExecutionSpec persisted', async () => {
      const { pool, state } = createMockTransactionalPool({ failAtCreateSpec: true });
      const service = new TaskIntakeService(pool);

      await expect(
        service.processIntake({ rawRequest: 'Will fail on spec creation' })
      ).rejects.toThrow('Simulated execution_specs table INSERT failure');

      expect(state.transactionsBegan).toBe(1);
      expect(state.transactionsCommitted).toBe(0);
      expect(state.transactionsRolledBack).toBe(1);
      expect(state.clientsReleased).toBe(1);
      expect(state.tasks.size).toBe(0);
      expect(state.specs.size).toBe(0);
    });

    it('5. rollback on sealExecutionSpec failure: zero Task and zero ExecutionSpec persisted', async () => {
      const { pool, state } = createMockTransactionalPool({ failAtSealSpec: true });
      const service = new TaskIntakeService(pool);

      await expect(
        service.processIntake({ rawRequest: 'Will fail on spec seal' })
      ).rejects.toThrow('Simulated execution_specs table SEAL UPDATE failure');

      expect(state.transactionsBegan).toBe(1);
      expect(state.transactionsCommitted).toBe(0);
      expect(state.transactionsRolledBack).toBe(1);
      expect(state.clientsReleased).toBe(1);
      expect(state.tasks.size).toBe(0);
      expect(state.specs.size).toBe(0);
    });

    it('6. client release on success: PoolClient.release() is called exactly once', async () => {
      const { pool, state } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      await service.processIntake({ rawRequest: 'Clean success flow' });
      expect(state.clientsReleased).toBe(1);
    });

    it('7. client release on failure: PoolClient.release() is called on commit failure', async () => {
      const { pool, state } = createMockTransactionalPool({ failAtCommit: true });
      const service = new TaskIntakeService(pool);

      await expect(
        service.processIntake({ rawRequest: 'Commit failure test' })
      ).rejects.toThrow('Simulated database COMMIT failure');

      expect(state.transactionsRolledBack).toBe(1);
      expect(state.clientsReleased).toBe(1);
      expect(state.tasks.size).toBe(0);
      expect(state.specs.size).toBe(0);
    });
  });

  describe('B. Canonical Lifecycle & Spec Integrity Contracts', () => {
    it('12. no duplicate sealing mechanism: uses canonical sealExecutionSpec', async () => {
      const { pool } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const result = await service.processIntake({
        rawRequest: 'Validate canonical sealing mechanism',
      });

      expect(result.executionSpec.status).toBe('SEALED');
      // Verify specContentJson was parsed and updated with canonical hash
      const content = JSON.parse(result.executionSpec.spec_content_json);
      expect(content.metadata.specHash).toBe(result.executionSpec.spec_hash);
    });

    it('13. no direct SEALED insert: initial spec insert is UNSEALED, seal produces SEALED', async () => {
      const { pool, state } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      await service.processIntake({
        rawRequest: 'Verify two-step canonical creation and sealing',
      });

      // The recorded insert status MUST be UNSEALED
      expect(state.recordedSpecStatusesOnInsert).toEqual(['UNSEALED']);
    });

    it('14. lineage preserved: intakeVersion, intakeHash, source, createdAt match normalized intake', async () => {
      const { pool } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const rawRequest = 'Add rate limiting to public endpoints';
      const normalized = normalizeTaskIntake({
        rawRequest,
        source: 'api-gateway',
        createdAt: '2026-09-11T12:00:00.000Z',
      });

      const result = await service.processIntake(normalized);

      expect(result.executionSpec.lineage.intakeVersion).toBe('1.0.0');
      expect(result.executionSpec.lineage.intakeHash).toBe(normalized.lineage.intakeHash);
      expect(result.executionSpec.lineage.source).toBe('api-gateway');
      expect(result.executionSpec.lineage.createdAt).toBe('2026-09-11T12:00:00.000Z');
    });

    it('15. intakeHash preserved: distinct from task.id and execution_specs.spec_hash', async () => {
      const { pool } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const result = await service.processIntake({
        rawRequest: 'Audit three independent identity domains',
      });

      const taskId = result.task.id;
      const intakeHash = result.executionSpec.lineage.intakeHash;
      const specHash = result.executionSpec.spec_hash;

      // 3 independent domains
      expect(taskId).not.toBe(intakeHash);
      expect(taskId).not.toBe(specHash);
      expect(intakeHash).not.toBe(specHash);
    });

    it('16. specHash generated by canonical seal: equals computeSpecHash(spec)', async () => {
      const { pool } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const result = await service.processIntake({
        rawRequest: 'Verify canonical hash calculation',
      });

      const parsedSpec = JSON.parse(result.executionSpec.spec_content_json);
      const expectedHash = computeSpecHash(parsedSpec);

      expect(result.executionSpec.spec_hash).toBe(expectedHash);
    });

    it('17. Task remains QUEUED: task status in database is QUEUED', async () => {
      const { pool, state } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const result = await service.processIntake({
        rawRequest: 'Verify queue status preservation',
        priority: 3,
      });

      const dbTask = state.tasks.get(result.task.id);
      expect(dbTask.status).toBe('QUEUED');
      expect(dbTask.priority).toBe(3);
    });

    it('18. historical Tasks untouched: existing tasks without specs are not mutated', async () => {
      const historicalTask: Task = {
        id: 'task-historical-1',
        project: 'legacy-proj',
        repository: 'https://github.com/pub/legacy.git',
        objective: 'Legacy task from Phase 1',
        prompt: 'Do legacy work',
        status: 'COMPLETED',
        priority: 0,
        worker: 'worker-1',
        result: null,
        error: null,
        branch: null,
        commitSha: null,
        gitStatus: null,
        createdAt: new Date('2026-08-01T00:00:00Z'),
        updatedAt: new Date('2026-08-01T00:00:00Z'),
        leaseOwner: null,
        leaseDeadline: null,
        heartbeatAt: null,
        workspacePath: null,
        prototypeSessionId: null,
      };

      const { pool, state } = createMockTransactionalPool({
        tasks: new Map([['task-historical-1', historicalTask]]),
      });
      const service = new TaskIntakeService(pool);

      await service.processIntake({ rawRequest: 'New 3B task' });

      // Historical task is untouched
      const afterHistorical = state.tasks.get('task-historical-1');
      expect(afterHistorical.status).toBe('COMPLETED');
      expect(state.specs.has('task-historical-1')).toBe(false);
    });

    it('19. PP remains isolated: tasks without prototypeSessionId remain pure PDL', async () => {
      const { pool } = createMockTransactionalPool();
      const service = new TaskIntakeService(pool);

      const result = await service.processIntake({
        rawRequest: 'Verify PP isolation invariant',
      });

      expect(result.task.prototypeSessionId).toBeNull();
    });

    it('20. no migration required: schema works with 019_execution_specs.sql', () => {
      const spec = buildCanonicalExecutionSpec(
        normalizeTaskIntake({
          rawRequest: 'Verify no schema additions needed',
          source: 'unit-test',
          createdAt: new Date().toISOString(),
        })
      );
      expect(spec.specVersion).toBe(EXECUTION_SPEC_VERSION);
    });
  });

  describe('C. HTTP API Endpoint Contracts (POST /tasks)', () => {
    let server: Server;
    let baseUrl: string;

    const startAppWith = async (pool: PoolLike, intakeService?: TaskIntakeService): Promise<string> => {
      const app = createPdlApp(pool as any, undefined, intakeService ?? new TaskIntakeService(pool));
      return new Promise((resolve) => {
        server = app.listen(0, '127.0.0.1', () => {
          const addr = server.address();
          const port = typeof addr === 'object' && addr ? addr.port : 0;
          baseUrl = 'http://127.0.0.1:' + port;
          resolve(baseUrl);
        });
      });
    };

    afterEach(async () => {
      if (server) {
        await new Promise<void>((resolve) => server.close(() => resolve()));
      }
    });

    it('8. HTTP 201: successful intake returns 201 with Task QUEUED and ExecutionSpec SEALED', async () => {
      const { pool } = createMockTransactionalPool();
      await startAppWith(pool);

      const res = await fetch(baseUrl + '/tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: 'Implement payment webhook handler',
          project: 'pub-pay',
          priority: 2,
        }),
      });

      expect(res.status).toBe(201);
      const data = (await res.json()) as any;

      expect(data.task).toBeDefined();
      expect(data.task.id).toMatch(/^task-/);
      expect(data.task.status).toBe('QUEUED');

      expect(data.executionSpec).toBeDefined();
      expect(data.executionSpec.id).toBeDefined();
      expect(data.executionSpec.specVersion).toBe('1.0.0');
      expect(data.executionSpec.status).toBe('SEALED');
      expect(data.executionSpec.sealedAt).toBeDefined();
      expect(data.executionSpec.specHash).toBeDefined();
      expect(data.executionSpec.lineage).toBeDefined();
      expect(data.executionSpec.lineage.intakeVersion).toBe('1.0.0');
    });

    it('9. HTTP 400: empty prompt or objective returns 400 Bad Request before transaction', async () => {
      const { pool, state } = createMockTransactionalPool();
      await startAppWith(pool);

      const res = await fetch(baseUrl + '/tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: '   ',
        }),
      });

      expect(res.status).toBe(400);
      const data = (await res.json()) as any;
      expect(data.error).toContain('prompt or objective is required');

      // Zero transactions opened
      expect(state.transactionsBegan).toBe(0);
      expect(state.tasks.size).toBe(0);
    });

    it('10. HTTP 422: unprocessable ExecutionSpec validation failure returns 422', async () => {
      const { pool, state } = createMockTransactionalPool();

      // Create a service mock that throws validation error
      const mockService = new TaskIntakeService(pool);
      vi.spyOn(mockService, 'processIntake').mockImplementation(async () => {
        const err: any = new Error('ExecutionSpec validation failed: INVALID_VERSION');
        err.name = 'ExecutionSpecValidationError';
        err.issues = [{ path: '$.specVersion', code: 'INVALID_VERSION', message: 'Expected 1.0.0' }];
        throw err;
      });

      await startAppWith(pool, mockService);

      const res = await fetch(baseUrl + '/tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: 'Task with broken spec version',
        }),
      });

      expect(res.status).toBe(422);
      const data = (await res.json()) as any;
      expect(data.error).toContain('validation failed');
      expect(data.details).toHaveLength(1);
      expect(state.tasks.size).toBe(0);
    });

    it('11. HTTP 500: database/transaction failure returns 500 without leaking stack trace', async () => {
      const { pool, state } = createMockTransactionalPool({ failAtTaskInsert: true });
      await startAppWith(pool);

      const res = await fetch(baseUrl + '/tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: 'Valid prompt that encounters DB error',
        }),
      });

      expect(res.status).toBe(500);
      const data = (await res.json()) as any;
      expect(data.error).toBe('Failed to process task intake due to database transaction error');
      // Ensure stack trace is NOT leaked in JSON response
      expect(data.stack).toBeUndefined();
      expect(state.tasks.size).toBe(0);
      expect(state.specs.size).toBe(0);
    });
  });
});
