import { randomUUID } from 'node:crypto'; import { Pool } from 'pg'; import type { CreateTask, Task, TaskRepository, TaskStatus } from './domain.js';
const map = (r: any): Task => ({ ...r, priority:Number(r.priority), result:r.result ?? null, worker:r.worker ?? null, error:r.error ?? null, branch:r.branch ?? null, commitSha:r.commit_sha ?? null, gitStatus:r.git_status ?? null, createdAt:r.created_at, updatedAt:r.updated_at });
export class PostgresTaskRepository implements TaskRepository {
  constructor(private pool: Pool) {}
  async create(input: CreateTask) { const q = `INSERT INTO tasks (id,project,repository,objective,prompt,priority) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`; return map((await this.pool.query(q,[randomUUID(),input.project,input.repository,input.objective,input.prompt,input.priority ?? 0])).rows[0]); }
  async list() { return (await this.pool.query('SELECT * FROM tasks ORDER BY priority DESC, created_at ASC')).rows.map(map); }
  async get(id:string) { const r=await this.pool.query('SELECT * FROM tasks WHERE id=$1',[id]); return r.rows[0] ? map(r.rows[0]) : null; }
  async claim(worker:string) { const q=`WITH candidate AS (SELECT id FROM tasks WHERE status='QUEUED' ORDER BY priority DESC,created_at ASC FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE tasks SET status='ASSIGNED', worker=$1, updated_at=now() WHERE id=(SELECT id FROM candidate) RETURNING *`; const r=await this.pool.query(q,[worker]); return r.rows[0] ? map(r.rows[0]) : null; }
  async update(id:string, patch:Partial<Task>) { const allowed: Record<string,string>={ status:'status',worker:'worker',result:'result',error:'error',branch:'branch',commitSha:'commit_sha',gitStatus:'git_status' }; const entries=Object.entries(patch).filter(([k,v])=>allowed[k] && v !== undefined); if(!entries.length)return this.get(id); const set=entries.map(([k],i)=>`${allowed[k]}=$${i+2}`).join(', '); const values=entries.map(([,v])=>v); const r=await this.pool.query(`UPDATE tasks SET ${set}, updated_at=now() WHERE id=$1 RETURNING *`,[id,...values]); return r.rows[0]?map(r.rows[0]):null; }
  async cancel(id:string) { const r=await this.pool.query(`UPDATE tasks SET status='CANCELLED', updated_at=now() WHERE id=$1 AND status IN ('QUEUED','ASSIGNED') RETURNING *`,[id]); return r.rows[0]?map(r.rows[0]):null; }
  async retry(id:string) { const r=await this.pool.query(`UPDATE tasks SET status='QUEUED', worker=NULL, result=NULL, error=NULL, branch=NULL, commit_sha=NULL, git_status=NULL, updated_at=now() WHERE id=$1 AND status IN ('FAILED','BLOCKED','CANCELLED','NEEDS_REVIEW') RETURNING *`,[id]); return r.rows[0]?map(r.rows[0]):null; }
}
